# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/michelebigi/VisualStudio Code/GitHub/IOC_GaiaLib"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/michelebigi/VisualStudio Code/GitHub/IOC_GaiaLib"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/michelebigi/VisualStudio Code/GitHub/IOC_GaiaLib/CMakeFiles" "/Users/michelebigi/VisualStudio Code/GitHub/IOC_GaiaLib//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/michelebigi/VisualStudio Code/GitHub/IOC_GaiaLib/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ioc_gaialib

# Build rule for target.
ioc_gaialib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ioc_gaialib
.PHONY : ioc_gaialib

# fast build rule for target.
ioc_gaialib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/build
.PHONY : ioc_gaialib/fast

#=============================================================================
# Target rules for targets named comprehensive_test_suite

# Build rule for target.
comprehensive_test_suite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 comprehensive_test_suite
.PHONY : comprehensive_test_suite

# fast build rule for target.
comprehensive_test_suite/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/comprehensive_test_suite.dir/build.make CMakeFiles/comprehensive_test_suite.dir/build
.PHONY : comprehensive_test_suite/fast

#=============================================================================
# Target rules for targets named iau_integration_test

# Build rule for target.
iau_integration_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iau_integration_test
.PHONY : iau_integration_test

# fast build rule for target.
iau_integration_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iau_integration_test.dir/build.make CMakeFiles/iau_integration_test.dir/build
.PHONY : iau_integration_test/fast

#=============================================================================
# Target rules for targets named complete_performance_benchmark

# Build rule for target.
complete_performance_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 complete_performance_benchmark
.PHONY : complete_performance_benchmark

# fast build rule for target.
complete_performance_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complete_performance_benchmark.dir/build.make CMakeFiles/complete_performance_benchmark.dir/build
.PHONY : complete_performance_benchmark/fast

#=============================================================================
# Target rules for targets named simple_test

# Build rule for target.
simple_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_test
.PHONY : simple_test

# fast build rule for target.
simple_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/simple_test.dir/build.make examples/CMakeFiles/simple_test.dir/build
.PHONY : simple_test/fast

#=============================================================================
# Target rules for targets named integration_test

# Build rule for target.
integration_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 integration_test
.PHONY : integration_test

# fast build rule for target.
integration_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/integration_test.dir/build.make examples/CMakeFiles/integration_test.dir/build
.PHONY : integration_test/fast

#=============================================================================
# Target rules for targets named real_data_test

# Build rule for target.
real_data_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 real_data_test
.PHONY : real_data_test

# fast build rule for target.
real_data_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/real_data_test.dir/build.make examples/CMakeFiles/real_data_test.dir/build
.PHONY : real_data_test/fast

#=============================================================================
# Target rules for targets named compile_catalog

# Build rule for target.
compile_catalog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compile_catalog
.PHONY : compile_catalog

# fast build rule for target.
compile_catalog/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/compile_catalog.dir/build.make examples/CMakeFiles/compile_catalog.dir/build
.PHONY : compile_catalog/fast

#=============================================================================
# Target rules for targets named test_catalog_query

# Build rule for target.
test_catalog_query: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_catalog_query
.PHONY : test_catalog_query

# fast build rule for target.
test_catalog_query/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_catalog_query.dir/build.make examples/CMakeFiles/test_catalog_query.dir/build
.PHONY : test_catalog_query/fast

#=============================================================================
# Target rules for targets named quick_catalog_test

# Build rule for target.
quick_catalog_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick_catalog_test
.PHONY : quick_catalog_test

# fast build rule for target.
quick_catalog_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/quick_catalog_test.dir/build.make examples/CMakeFiles/quick_catalog_test.dir/build
.PHONY : quick_catalog_test/fast

#=============================================================================
# Target rules for targets named test_mag17

# Build rule for target.
test_mag17: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mag17
.PHONY : test_mag17

# fast build rule for target.
test_mag17/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_mag17.dir/build.make examples/CMakeFiles/test_mag17.dir/build
.PHONY : test_mag17/fast

#=============================================================================
# Target rules for targets named test_grappa

# Build rule for target.
test_grappa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_grappa
.PHONY : test_grappa

# fast build rule for target.
test_grappa/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_grappa.dir/build.make examples/CMakeFiles/test_grappa.dir/build
.PHONY : test_grappa/fast

#=============================================================================
# Target rules for targets named test_local_catalog

# Build rule for target.
test_local_catalog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_local_catalog
.PHONY : test_local_catalog

# fast build rule for target.
test_local_catalog/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_local_catalog.dir/build.make examples/CMakeFiles/test_local_catalog.dir/build
.PHONY : test_local_catalog/fast

#=============================================================================
# Target rules for targets named simple_local_test

# Build rule for target.
simple_local_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_local_test
.PHONY : simple_local_test

# fast build rule for target.
simple_local_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/simple_local_test.dir/build.make examples/CMakeFiles/simple_local_test.dir/build
.PHONY : simple_local_test/fast

#=============================================================================
# Target rules for targets named comprehensive_local_test

# Build rule for target.
comprehensive_local_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 comprehensive_local_test
.PHONY : comprehensive_local_test

# fast build rule for target.
comprehensive_local_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/comprehensive_local_test.dir/build.make examples/CMakeFiles/comprehensive_local_test.dir/build
.PHONY : comprehensive_local_test/fast

#=============================================================================
# Target rules for targets named build_mag18_catalog

# Build rule for target.
build_mag18_catalog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_mag18_catalog
.PHONY : build_mag18_catalog

# fast build rule for target.
build_mag18_catalog/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/build_mag18_catalog.dir/build.make examples/CMakeFiles/build_mag18_catalog.dir/build
.PHONY : build_mag18_catalog/fast

#=============================================================================
# Target rules for targets named test_mag18_catalog

# Build rule for target.
test_mag18_catalog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mag18_catalog
.PHONY : test_mag18_catalog

# fast build rule for target.
test_mag18_catalog/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_mag18_catalog.dir/build.make examples/CMakeFiles/test_mag18_catalog.dir/build
.PHONY : test_mag18_catalog/fast

#=============================================================================
# Target rules for targets named test_unified_catalog

# Build rule for target.
test_unified_catalog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_unified_catalog
.PHONY : test_unified_catalog

# fast build rule for target.
test_unified_catalog/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_unified_catalog.dir/build.make examples/CMakeFiles/test_unified_catalog.dir/build
.PHONY : test_unified_catalog/fast

#=============================================================================
# Target rules for targets named analyze_mag18

# Build rule for target.
analyze_mag18: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 analyze_mag18
.PHONY : analyze_mag18

# fast build rule for target.
analyze_mag18/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/analyze_mag18.dir/build.make examples/CMakeFiles/analyze_mag18.dir/build
.PHONY : analyze_mag18/fast

#=============================================================================
# Target rules for targets named build_mag18_catalog_v2

# Build rule for target.
build_mag18_catalog_v2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_mag18_catalog_v2
.PHONY : build_mag18_catalog_v2

# fast build rule for target.
build_mag18_catalog_v2/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/build_mag18_catalog_v2.dir/build.make examples/CMakeFiles/build_mag18_catalog_v2.dir/build
.PHONY : build_mag18_catalog_v2/fast

#=============================================================================
# Target rules for targets named test_grappa_load

# Build rule for target.
test_grappa_load: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_grappa_load
.PHONY : test_grappa_load

# fast build rule for target.
test_grappa_load/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_grappa_load.dir/build.make examples/CMakeFiles/test_grappa_load.dir/build
.PHONY : test_grappa_load/fast

#=============================================================================
# Target rules for targets named test_mag18_catalog_v2

# Build rule for target.
test_mag18_catalog_v2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mag18_catalog_v2
.PHONY : test_mag18_catalog_v2

# fast build rule for target.
test_mag18_catalog_v2/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_mag18_catalog_v2.dir/build.make examples/CMakeFiles/test_mag18_catalog_v2.dir/build
.PHONY : test_mag18_catalog_v2/fast

#=============================================================================
# Target rules for targets named test_mag18_parallel

# Build rule for target.
test_mag18_parallel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mag18_parallel
.PHONY : test_mag18_parallel

# fast build rule for target.
test_mag18_parallel/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_mag18_parallel.dir/build.make examples/CMakeFiles/test_mag18_parallel.dir/build
.PHONY : test_mag18_parallel/fast

#=============================================================================
# Target rules for targets named test_openmp_quick

# Build rule for target.
test_openmp_quick: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_openmp_quick
.PHONY : test_openmp_quick

# fast build rule for target.
test_openmp_quick/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_openmp_quick.dir/build.make examples/CMakeFiles/test_openmp_quick.dir/build
.PHONY : test_openmp_quick/fast

#=============================================================================
# Target rules for targets named use_v1_catalog

# Build rule for target.
use_v1_catalog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 use_v1_catalog
.PHONY : use_v1_catalog

# fast build rule for target.
use_v1_catalog/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/use_v1_catalog.dir/build.make examples/CMakeFiles/use_v1_catalog.dir/build
.PHONY : use_v1_catalog/fast

#=============================================================================
# Target rules for targets named validate_v2_interface

# Build rule for target.
validate_v2_interface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 validate_v2_interface
.PHONY : validate_v2_interface

# fast build rule for target.
validate_v2_interface/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/validate_v2_interface.dir/build.make examples/CMakeFiles/validate_v2_interface.dir/build
.PHONY : validate_v2_interface/fast

#=============================================================================
# Target rules for targets named quick_v2_test

# Build rule for target.
quick_v2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick_v2_test
.PHONY : quick_v2_test

# fast build rule for target.
quick_v2_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/quick_v2_test.dir/build.make examples/CMakeFiles/quick_v2_test.dir/build
.PHONY : quick_v2_test/fast

#=============================================================================
# Target rules for targets named test_v2_minimal

# Build rule for target.
test_v2_minimal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_v2_minimal
.PHONY : test_v2_minimal

# fast build rule for target.
test_v2_minimal/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_v2_minimal.dir/build.make examples/CMakeFiles/test_v2_minimal.dir/build
.PHONY : test_v2_minimal/fast

#=============================================================================
# Target rules for targets named test_v2_io

# Build rule for target.
test_v2_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_v2_io
.PHONY : test_v2_io

# fast build rule for target.
test_v2_io/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_v2_io.dir/build.make examples/CMakeFiles/test_v2_io.dir/build
.PHONY : test_v2_io/fast

#=============================================================================
# Target rules for targets named profile_v2_load

# Build rule for target.
profile_v2_load: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 profile_v2_load
.PHONY : profile_v2_load

# fast build rule for target.
profile_v2_load/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/profile_v2_load.dir/build.make examples/CMakeFiles/profile_v2_load.dir/build
.PHONY : profile_v2_load/fast

#=============================================================================
# Target rules for targets named test_v2_lazyload

# Build rule for target.
test_v2_lazyload: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_v2_lazyload
.PHONY : test_v2_lazyload

# fast build rule for target.
test_v2_lazyload/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_v2_lazyload.dir/build.make examples/CMakeFiles/test_v2_lazyload.dir/build
.PHONY : test_v2_lazyload/fast

#=============================================================================
# Target rules for targets named simple_v2_test

# Build rule for target.
simple_v2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_v2_test
.PHONY : simple_v2_test

# fast build rule for target.
simple_v2_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/simple_v2_test.dir/build.make examples/CMakeFiles/simple_v2_test.dir/build
.PHONY : simple_v2_test/fast

#=============================================================================
# Target rules for targets named test_v2_complete

# Build rule for target.
test_v2_complete: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_v2_complete
.PHONY : test_v2_complete

# fast build rule for target.
test_v2_complete/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_v2_complete.dir/build.make examples/CMakeFiles/test_v2_complete.dir/build
.PHONY : test_v2_complete/fast

#=============================================================================
# Target rules for targets named decompress_v2_catalog

# Build rule for target.
decompress_v2_catalog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 decompress_v2_catalog
.PHONY : decompress_v2_catalog

# fast build rule for target.
decompress_v2_catalog/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/decompress_v2_catalog.dir/build.make examples/CMakeFiles/decompress_v2_catalog.dir/build
.PHONY : decompress_v2_catalog/fast

#=============================================================================
# Target rules for targets named test_uncompressed_v2

# Build rule for target.
test_uncompressed_v2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_uncompressed_v2
.PHONY : test_uncompressed_v2

# fast build rule for target.
test_uncompressed_v2/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_uncompressed_v2.dir/build.make examples/CMakeFiles/test_uncompressed_v2.dir/build
.PHONY : test_uncompressed_v2/fast

#=============================================================================
# Target rules for targets named timing_test_compressed

# Build rule for target.
timing_test_compressed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timing_test_compressed
.PHONY : timing_test_compressed

# fast build rule for target.
timing_test_compressed/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/timing_test_compressed.dir/build.make examples/CMakeFiles/timing_test_compressed.dir/build
.PHONY : timing_test_compressed/fast

#=============================================================================
# Target rules for targets named test_v2_interface_complete

# Build rule for target.
test_v2_interface_complete: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_v2_interface_complete
.PHONY : test_v2_interface_complete

# fast build rule for target.
test_v2_interface_complete/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_v2_interface_complete.dir/build.make examples/CMakeFiles/test_v2_interface_complete.dir/build
.PHONY : test_v2_interface_complete/fast

#=============================================================================
# Target rules for targets named test_cache_performance

# Build rule for target.
test_cache_performance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cache_performance
.PHONY : test_cache_performance

# fast build rule for target.
test_cache_performance/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_cache_performance.dir/build.make examples/CMakeFiles/test_cache_performance.dir/build
.PHONY : test_cache_performance/fast

#=============================================================================
# Target rules for targets named create_multifile_v2

# Build rule for target.
create_multifile_v2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 create_multifile_v2
.PHONY : create_multifile_v2

# fast build rule for target.
create_multifile_v2/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/create_multifile_v2.dir/build.make examples/CMakeFiles/create_multifile_v2.dir/build
.PHONY : create_multifile_v2/fast

#=============================================================================
# Target rules for targets named create_smart_multifile_v2

# Build rule for target.
create_smart_multifile_v2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 create_smart_multifile_v2
.PHONY : create_smart_multifile_v2

# fast build rule for target.
create_smart_multifile_v2/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/create_smart_multifile_v2.dir/build.make examples/CMakeFiles/create_smart_multifile_v2.dir/build
.PHONY : create_smart_multifile_v2/fast

#=============================================================================
# Target rules for targets named test_multifile_performance

# Build rule for target.
test_multifile_performance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_multifile_performance
.PHONY : test_multifile_performance

# fast build rule for target.
test_multifile_performance/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_multifile_performance.dir/build.make examples/CMakeFiles/test_multifile_performance.dir/build
.PHONY : test_multifile_performance/fast

#=============================================================================
# Target rules for targets named debug_multifile

# Build rule for target.
debug_multifile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug_multifile
.PHONY : debug_multifile

# fast build rule for target.
debug_multifile/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/debug_multifile.dir/build.make examples/CMakeFiles/debug_multifile.dir/build
.PHONY : debug_multifile/fast

#=============================================================================
# Target rules for targets named raw_chunk_test

# Build rule for target.
raw_chunk_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raw_chunk_test
.PHONY : raw_chunk_test

# fast build rule for target.
raw_chunk_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/raw_chunk_test.dir/build.make examples/CMakeFiles/raw_chunk_test.dir/build
.PHONY : raw_chunk_test/fast

#=============================================================================
# Target rules for targets named targeted_search_test

# Build rule for target.
targeted_search_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 targeted_search_test
.PHONY : targeted_search_test

# fast build rule for target.
targeted_search_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/targeted_search_test.dir/build.make examples/CMakeFiles/targeted_search_test.dir/build
.PHONY : targeted_search_test/fast

#=============================================================================
# Target rules for targets named final_validation

# Build rule for target.
final_validation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 final_validation
.PHONY : final_validation

# fast build rule for target.
final_validation/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/final_validation.dir/build.make examples/CMakeFiles/final_validation.dir/build
.PHONY : final_validation/fast

#=============================================================================
# Target rules for targets named concurrency_test

# Build rule for target.
concurrency_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 concurrency_test
.PHONY : concurrency_test

# fast build rule for target.
concurrency_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/concurrency_test.dir/build.make examples/CMakeFiles/concurrency_test.dir/build
.PHONY : concurrency_test/fast

#=============================================================================
# Target rules for targets named concurrent_comparison

# Build rule for target.
concurrent_comparison: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 concurrent_comparison
.PHONY : concurrent_comparison

# fast build rule for target.
concurrent_comparison/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/concurrent_comparison.dir/build.make examples/CMakeFiles/concurrent_comparison.dir/build
.PHONY : concurrent_comparison/fast

#=============================================================================
# Target rules for targets named unified_api_demo

# Build rule for target.
unified_api_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unified_api_demo
.PHONY : unified_api_demo

# fast build rule for target.
unified_api_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/unified_api_demo.dir/build.make examples/CMakeFiles/unified_api_demo.dir/build
.PHONY : unified_api_demo/fast

#=============================================================================
# Target rules for targets named migration_guide

# Build rule for target.
migration_guide: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 migration_guide
.PHONY : migration_guide

# fast build rule for target.
migration_guide/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/migration_guide.dir/build.make examples/CMakeFiles/migration_guide.dir/build
.PHONY : migration_guide/fast

#=============================================================================
# Target rules for targets named cross_match_demo

# Build rule for target.
cross_match_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cross_match_demo
.PHONY : cross_match_demo

# fast build rule for target.
cross_match_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/cross_match_demo.dir/build.make examples/CMakeFiles/cross_match_demo.dir/build
.PHONY : cross_match_demo/fast

#=============================================================================
# Target rules for targets named deprecation_test

# Build rule for target.
deprecation_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 deprecation_test
.PHONY : deprecation_test

# fast build rule for target.
deprecation_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/deprecation_test.dir/build.make examples/CMakeFiles/deprecation_test.dir/build
.PHONY : deprecation_test/fast

#=============================================================================
# Target rules for targets named test_crossmatch

# Build rule for target.
test_crossmatch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_crossmatch
.PHONY : test_crossmatch

# fast build rule for target.
test_crossmatch/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_crossmatch.dir/build.make examples/CMakeFiles/test_crossmatch.dir/build
.PHONY : test_crossmatch/fast

examples/complete_performance_benchmark.o: examples/complete_performance_benchmark.cpp.o
.PHONY : examples/complete_performance_benchmark.o

# target to build an object file
examples/complete_performance_benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complete_performance_benchmark.dir/build.make CMakeFiles/complete_performance_benchmark.dir/examples/complete_performance_benchmark.cpp.o
.PHONY : examples/complete_performance_benchmark.cpp.o

examples/complete_performance_benchmark.i: examples/complete_performance_benchmark.cpp.i
.PHONY : examples/complete_performance_benchmark.i

# target to preprocess a source file
examples/complete_performance_benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complete_performance_benchmark.dir/build.make CMakeFiles/complete_performance_benchmark.dir/examples/complete_performance_benchmark.cpp.i
.PHONY : examples/complete_performance_benchmark.cpp.i

examples/complete_performance_benchmark.s: examples/complete_performance_benchmark.cpp.s
.PHONY : examples/complete_performance_benchmark.s

# target to generate assembly for a file
examples/complete_performance_benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/complete_performance_benchmark.dir/build.make CMakeFiles/complete_performance_benchmark.dir/examples/complete_performance_benchmark.cpp.s
.PHONY : examples/complete_performance_benchmark.cpp.s

examples/comprehensive_test_suite.o: examples/comprehensive_test_suite.cpp.o
.PHONY : examples/comprehensive_test_suite.o

# target to build an object file
examples/comprehensive_test_suite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/comprehensive_test_suite.dir/build.make CMakeFiles/comprehensive_test_suite.dir/examples/comprehensive_test_suite.cpp.o
.PHONY : examples/comprehensive_test_suite.cpp.o

examples/comprehensive_test_suite.i: examples/comprehensive_test_suite.cpp.i
.PHONY : examples/comprehensive_test_suite.i

# target to preprocess a source file
examples/comprehensive_test_suite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/comprehensive_test_suite.dir/build.make CMakeFiles/comprehensive_test_suite.dir/examples/comprehensive_test_suite.cpp.i
.PHONY : examples/comprehensive_test_suite.cpp.i

examples/comprehensive_test_suite.s: examples/comprehensive_test_suite.cpp.s
.PHONY : examples/comprehensive_test_suite.s

# target to generate assembly for a file
examples/comprehensive_test_suite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/comprehensive_test_suite.dir/build.make CMakeFiles/comprehensive_test_suite.dir/examples/comprehensive_test_suite.cpp.s
.PHONY : examples/comprehensive_test_suite.cpp.s

examples/iau_integration_test.o: examples/iau_integration_test.cpp.o
.PHONY : examples/iau_integration_test.o

# target to build an object file
examples/iau_integration_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iau_integration_test.dir/build.make CMakeFiles/iau_integration_test.dir/examples/iau_integration_test.cpp.o
.PHONY : examples/iau_integration_test.cpp.o

examples/iau_integration_test.i: examples/iau_integration_test.cpp.i
.PHONY : examples/iau_integration_test.i

# target to preprocess a source file
examples/iau_integration_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iau_integration_test.dir/build.make CMakeFiles/iau_integration_test.dir/examples/iau_integration_test.cpp.i
.PHONY : examples/iau_integration_test.cpp.i

examples/iau_integration_test.s: examples/iau_integration_test.cpp.s
.PHONY : examples/iau_integration_test.s

# target to generate assembly for a file
examples/iau_integration_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iau_integration_test.dir/build.make CMakeFiles/iau_integration_test.dir/examples/iau_integration_test.cpp.s
.PHONY : examples/iau_integration_test.cpp.s

src/catalog_compiler.o: src/catalog_compiler.cpp.o
.PHONY : src/catalog_compiler.o

# target to build an object file
src/catalog_compiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/catalog_compiler.cpp.o
.PHONY : src/catalog_compiler.cpp.o

src/catalog_compiler.i: src/catalog_compiler.cpp.i
.PHONY : src/catalog_compiler.i

# target to preprocess a source file
src/catalog_compiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/catalog_compiler.cpp.i
.PHONY : src/catalog_compiler.cpp.i

src/catalog_compiler.s: src/catalog_compiler.cpp.s
.PHONY : src/catalog_compiler.s

# target to generate assembly for a file
src/catalog_compiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/catalog_compiler.cpp.s
.PHONY : src/catalog_compiler.cpp.s

src/common_star_names.o: src/common_star_names.cpp.o
.PHONY : src/common_star_names.o

# target to build an object file
src/common_star_names.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/common_star_names.cpp.o
.PHONY : src/common_star_names.cpp.o

src/common_star_names.i: src/common_star_names.cpp.i
.PHONY : src/common_star_names.i

# target to preprocess a source file
src/common_star_names.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/common_star_names.cpp.i
.PHONY : src/common_star_names.cpp.i

src/common_star_names.s: src/common_star_names.cpp.s
.PHONY : src/common_star_names.s

# target to generate assembly for a file
src/common_star_names.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/common_star_names.cpp.s
.PHONY : src/common_star_names.cpp.s

src/concurrent_multifile_catalog_v2.o: src/concurrent_multifile_catalog_v2.cpp.o
.PHONY : src/concurrent_multifile_catalog_v2.o

# target to build an object file
src/concurrent_multifile_catalog_v2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/concurrent_multifile_catalog_v2.cpp.o
.PHONY : src/concurrent_multifile_catalog_v2.cpp.o

src/concurrent_multifile_catalog_v2.i: src/concurrent_multifile_catalog_v2.cpp.i
.PHONY : src/concurrent_multifile_catalog_v2.i

# target to preprocess a source file
src/concurrent_multifile_catalog_v2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/concurrent_multifile_catalog_v2.cpp.i
.PHONY : src/concurrent_multifile_catalog_v2.cpp.i

src/concurrent_multifile_catalog_v2.s: src/concurrent_multifile_catalog_v2.cpp.s
.PHONY : src/concurrent_multifile_catalog_v2.s

# target to generate assembly for a file
src/concurrent_multifile_catalog_v2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/concurrent_multifile_catalog_v2.cpp.s
.PHONY : src/concurrent_multifile_catalog_v2.cpp.s

src/gaia_cache.o: src/gaia_cache.cpp.o
.PHONY : src/gaia_cache.o

# target to build an object file
src/gaia_cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_cache.cpp.o
.PHONY : src/gaia_cache.cpp.o

src/gaia_cache.i: src/gaia_cache.cpp.i
.PHONY : src/gaia_cache.i

# target to preprocess a source file
src/gaia_cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_cache.cpp.i
.PHONY : src/gaia_cache.cpp.i

src/gaia_cache.s: src/gaia_cache.cpp.s
.PHONY : src/gaia_cache.s

# target to generate assembly for a file
src/gaia_cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_cache.cpp.s
.PHONY : src/gaia_cache.cpp.s

src/gaia_catalog.o: src/gaia_catalog.cpp.o
.PHONY : src/gaia_catalog.o

# target to build an object file
src/gaia_catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_catalog.cpp.o
.PHONY : src/gaia_catalog.cpp.o

src/gaia_catalog.i: src/gaia_catalog.cpp.i
.PHONY : src/gaia_catalog.i

# target to preprocess a source file
src/gaia_catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_catalog.cpp.i
.PHONY : src/gaia_catalog.cpp.i

src/gaia_catalog.s: src/gaia_catalog.cpp.s
.PHONY : src/gaia_catalog.s

# target to generate assembly for a file
src/gaia_catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_catalog.cpp.s
.PHONY : src/gaia_catalog.cpp.s

src/gaia_client.o: src/gaia_client.cpp.o
.PHONY : src/gaia_client.o

# target to build an object file
src/gaia_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_client.cpp.o
.PHONY : src/gaia_client.cpp.o

src/gaia_client.i: src/gaia_client.cpp.i
.PHONY : src/gaia_client.i

# target to preprocess a source file
src/gaia_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_client.cpp.i
.PHONY : src/gaia_client.cpp.i

src/gaia_client.s: src/gaia_client.cpp.s
.PHONY : src/gaia_client.s

# target to generate assembly for a file
src/gaia_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_client.cpp.s
.PHONY : src/gaia_client.cpp.s

src/gaia_local_catalog.o: src/gaia_local_catalog.cpp.o
.PHONY : src/gaia_local_catalog.o

# target to build an object file
src/gaia_local_catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_local_catalog.cpp.o
.PHONY : src/gaia_local_catalog.cpp.o

src/gaia_local_catalog.i: src/gaia_local_catalog.cpp.i
.PHONY : src/gaia_local_catalog.i

# target to preprocess a source file
src/gaia_local_catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_local_catalog.cpp.i
.PHONY : src/gaia_local_catalog.cpp.i

src/gaia_local_catalog.s: src/gaia_local_catalog.cpp.s
.PHONY : src/gaia_local_catalog.s

# target to generate assembly for a file
src/gaia_local_catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_local_catalog.cpp.s
.PHONY : src/gaia_local_catalog.cpp.s

src/gaia_mag18_catalog.o: src/gaia_mag18_catalog.cpp.o
.PHONY : src/gaia_mag18_catalog.o

# target to build an object file
src/gaia_mag18_catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog.cpp.o
.PHONY : src/gaia_mag18_catalog.cpp.o

src/gaia_mag18_catalog.i: src/gaia_mag18_catalog.cpp.i
.PHONY : src/gaia_mag18_catalog.i

# target to preprocess a source file
src/gaia_mag18_catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog.cpp.i
.PHONY : src/gaia_mag18_catalog.cpp.i

src/gaia_mag18_catalog.s: src/gaia_mag18_catalog.cpp.s
.PHONY : src/gaia_mag18_catalog.s

# target to generate assembly for a file
src/gaia_mag18_catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog.cpp.s
.PHONY : src/gaia_mag18_catalog.cpp.s

src/gaia_mag18_catalog_v2.o: src/gaia_mag18_catalog_v2.cpp.o
.PHONY : src/gaia_mag18_catalog_v2.o

# target to build an object file
src/gaia_mag18_catalog_v2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog_v2.cpp.o
.PHONY : src/gaia_mag18_catalog_v2.cpp.o

src/gaia_mag18_catalog_v2.i: src/gaia_mag18_catalog_v2.cpp.i
.PHONY : src/gaia_mag18_catalog_v2.i

# target to preprocess a source file
src/gaia_mag18_catalog_v2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog_v2.cpp.i
.PHONY : src/gaia_mag18_catalog_v2.cpp.i

src/gaia_mag18_catalog_v2.s: src/gaia_mag18_catalog_v2.cpp.s
.PHONY : src/gaia_mag18_catalog_v2.s

# target to generate assembly for a file
src/gaia_mag18_catalog_v2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog_v2.cpp.s
.PHONY : src/gaia_mag18_catalog_v2.cpp.s

src/grappa_reader.o: src/grappa_reader.cpp.o
.PHONY : src/grappa_reader.o

# target to build an object file
src/grappa_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/grappa_reader.cpp.o
.PHONY : src/grappa_reader.cpp.o

src/grappa_reader.i: src/grappa_reader.cpp.i
.PHONY : src/grappa_reader.i

# target to preprocess a source file
src/grappa_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/grappa_reader.cpp.i
.PHONY : src/grappa_reader.cpp.i

src/grappa_reader.s: src/grappa_reader.cpp.s
.PHONY : src/grappa_reader.s

# target to generate assembly for a file
src/grappa_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/grappa_reader.cpp.s
.PHONY : src/grappa_reader.cpp.s

src/iau_star_catalog_parser.o: src/iau_star_catalog_parser.cpp.o
.PHONY : src/iau_star_catalog_parser.o

# target to build an object file
src/iau_star_catalog_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/iau_star_catalog_parser.cpp.o
.PHONY : src/iau_star_catalog_parser.cpp.o

src/iau_star_catalog_parser.i: src/iau_star_catalog_parser.cpp.i
.PHONY : src/iau_star_catalog_parser.i

# target to preprocess a source file
src/iau_star_catalog_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/iau_star_catalog_parser.cpp.i
.PHONY : src/iau_star_catalog_parser.cpp.i

src/iau_star_catalog_parser.s: src/iau_star_catalog_parser.cpp.s
.PHONY : src/iau_star_catalog_parser.s

# target to generate assembly for a file
src/iau_star_catalog_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/iau_star_catalog_parser.cpp.s
.PHONY : src/iau_star_catalog_parser.cpp.s

src/multifile_catalog_v2.o: src/multifile_catalog_v2.cpp.o
.PHONY : src/multifile_catalog_v2.o

# target to build an object file
src/multifile_catalog_v2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/multifile_catalog_v2.cpp.o
.PHONY : src/multifile_catalog_v2.cpp.o

src/multifile_catalog_v2.i: src/multifile_catalog_v2.cpp.i
.PHONY : src/multifile_catalog_v2.i

# target to preprocess a source file
src/multifile_catalog_v2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/multifile_catalog_v2.cpp.i
.PHONY : src/multifile_catalog_v2.cpp.i

src/multifile_catalog_v2.s: src/multifile_catalog_v2.cpp.s
.PHONY : src/multifile_catalog_v2.s

# target to generate assembly for a file
src/multifile_catalog_v2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/multifile_catalog_v2.cpp.s
.PHONY : src/multifile_catalog_v2.cpp.s

src/types.o: src/types.cpp.o
.PHONY : src/types.o

# target to build an object file
src/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/types.cpp.o
.PHONY : src/types.cpp.o

src/types.i: src/types.cpp.i
.PHONY : src/types.i

# target to preprocess a source file
src/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/types.cpp.i
.PHONY : src/types.cpp.i

src/types.s: src/types.cpp.s
.PHONY : src/types.s

# target to generate assembly for a file
src/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/types.cpp.s
.PHONY : src/types.cpp.s

src/unified_gaia_catalog.o: src/unified_gaia_catalog.cpp.o
.PHONY : src/unified_gaia_catalog.o

# target to build an object file
src/unified_gaia_catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/unified_gaia_catalog.cpp.o
.PHONY : src/unified_gaia_catalog.cpp.o

src/unified_gaia_catalog.i: src/unified_gaia_catalog.cpp.i
.PHONY : src/unified_gaia_catalog.i

# target to preprocess a source file
src/unified_gaia_catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/unified_gaia_catalog.cpp.i
.PHONY : src/unified_gaia_catalog.cpp.i

src/unified_gaia_catalog.s: src/unified_gaia_catalog.cpp.s
.PHONY : src/unified_gaia_catalog.s

# target to generate assembly for a file
src/unified_gaia_catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/unified_gaia_catalog.cpp.s
.PHONY : src/unified_gaia_catalog.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... analyze_mag18"
	@echo "... build_mag18_catalog"
	@echo "... build_mag18_catalog_v2"
	@echo "... compile_catalog"
	@echo "... complete_performance_benchmark"
	@echo "... comprehensive_local_test"
	@echo "... comprehensive_test_suite"
	@echo "... concurrency_test"
	@echo "... concurrent_comparison"
	@echo "... create_multifile_v2"
	@echo "... create_smart_multifile_v2"
	@echo "... cross_match_demo"
	@echo "... debug_multifile"
	@echo "... decompress_v2_catalog"
	@echo "... deprecation_test"
	@echo "... final_validation"
	@echo "... iau_integration_test"
	@echo "... integration_test"
	@echo "... ioc_gaialib"
	@echo "... migration_guide"
	@echo "... profile_v2_load"
	@echo "... quick_catalog_test"
	@echo "... quick_v2_test"
	@echo "... raw_chunk_test"
	@echo "... real_data_test"
	@echo "... simple_local_test"
	@echo "... simple_test"
	@echo "... simple_v2_test"
	@echo "... targeted_search_test"
	@echo "... test_cache_performance"
	@echo "... test_catalog_query"
	@echo "... test_crossmatch"
	@echo "... test_grappa"
	@echo "... test_grappa_load"
	@echo "... test_local_catalog"
	@echo "... test_mag17"
	@echo "... test_mag18_catalog"
	@echo "... test_mag18_catalog_v2"
	@echo "... test_mag18_parallel"
	@echo "... test_multifile_performance"
	@echo "... test_openmp_quick"
	@echo "... test_uncompressed_v2"
	@echo "... test_unified_catalog"
	@echo "... test_v2_complete"
	@echo "... test_v2_interface_complete"
	@echo "... test_v2_io"
	@echo "... test_v2_lazyload"
	@echo "... test_v2_minimal"
	@echo "... timing_test_compressed"
	@echo "... unified_api_demo"
	@echo "... use_v1_catalog"
	@echo "... validate_v2_interface"
	@echo "... examples/complete_performance_benchmark.o"
	@echo "... examples/complete_performance_benchmark.i"
	@echo "... examples/complete_performance_benchmark.s"
	@echo "... examples/comprehensive_test_suite.o"
	@echo "... examples/comprehensive_test_suite.i"
	@echo "... examples/comprehensive_test_suite.s"
	@echo "... examples/iau_integration_test.o"
	@echo "... examples/iau_integration_test.i"
	@echo "... examples/iau_integration_test.s"
	@echo "... src/catalog_compiler.o"
	@echo "... src/catalog_compiler.i"
	@echo "... src/catalog_compiler.s"
	@echo "... src/common_star_names.o"
	@echo "... src/common_star_names.i"
	@echo "... src/common_star_names.s"
	@echo "... src/concurrent_multifile_catalog_v2.o"
	@echo "... src/concurrent_multifile_catalog_v2.i"
	@echo "... src/concurrent_multifile_catalog_v2.s"
	@echo "... src/gaia_cache.o"
	@echo "... src/gaia_cache.i"
	@echo "... src/gaia_cache.s"
	@echo "... src/gaia_catalog.o"
	@echo "... src/gaia_catalog.i"
	@echo "... src/gaia_catalog.s"
	@echo "... src/gaia_client.o"
	@echo "... src/gaia_client.i"
	@echo "... src/gaia_client.s"
	@echo "... src/gaia_local_catalog.o"
	@echo "... src/gaia_local_catalog.i"
	@echo "... src/gaia_local_catalog.s"
	@echo "... src/gaia_mag18_catalog.o"
	@echo "... src/gaia_mag18_catalog.i"
	@echo "... src/gaia_mag18_catalog.s"
	@echo "... src/gaia_mag18_catalog_v2.o"
	@echo "... src/gaia_mag18_catalog_v2.i"
	@echo "... src/gaia_mag18_catalog_v2.s"
	@echo "... src/grappa_reader.o"
	@echo "... src/grappa_reader.i"
	@echo "... src/grappa_reader.s"
	@echo "... src/iau_star_catalog_parser.o"
	@echo "... src/iau_star_catalog_parser.i"
	@echo "... src/iau_star_catalog_parser.s"
	@echo "... src/multifile_catalog_v2.o"
	@echo "... src/multifile_catalog_v2.i"
	@echo "... src/multifile_catalog_v2.s"
	@echo "... src/types.o"
	@echo "... src/types.i"
	@echo "... src/types.s"
	@echo "... src/unified_gaia_catalog.o"
	@echo "... src/unified_gaia_catalog.i"
	@echo "... src/unified_gaia_catalog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

