# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/michelebigi/VisualStudio Code/GitHub/IOC_GaiaLib"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/michelebigi/VisualStudio Code/GitHub/IOC_GaiaLib"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/michelebigi/VisualStudio Code/GitHub/IOC_GaiaLib/CMakeFiles" "/Users/michelebigi/VisualStudio Code/GitHub/IOC_GaiaLib//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/michelebigi/VisualStudio Code/GitHub/IOC_GaiaLib/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ioc_gaialib

# Build rule for target.
ioc_gaialib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ioc_gaialib
.PHONY : ioc_gaialib

# fast build rule for target.
ioc_gaialib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/build
.PHONY : ioc_gaialib/fast

#=============================================================================
# Target rules for targets named unified_api_demo

# Build rule for target.
unified_api_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unified_api_demo
.PHONY : unified_api_demo

# fast build rule for target.
unified_api_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/unified_api_demo.dir/build.make examples/CMakeFiles/unified_api_demo.dir/build
.PHONY : unified_api_demo/fast

#=============================================================================
# Target rules for targets named iau_integration_test

# Build rule for target.
iau_integration_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iau_integration_test
.PHONY : iau_integration_test

# fast build rule for target.
iau_integration_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/iau_integration_test.dir/build.make examples/CMakeFiles/iau_integration_test.dir/build
.PHONY : iau_integration_test/fast

#=============================================================================
# Target rules for targets named integration_test

# Build rule for target.
integration_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 integration_test
.PHONY : integration_test

# fast build rule for target.
integration_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/integration_test.dir/build.make examples/CMakeFiles/integration_test.dir/build
.PHONY : integration_test/fast

src/common_star_names.o: src/common_star_names.cpp.o
.PHONY : src/common_star_names.o

# target to build an object file
src/common_star_names.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/common_star_names.cpp.o
.PHONY : src/common_star_names.cpp.o

src/common_star_names.i: src/common_star_names.cpp.i
.PHONY : src/common_star_names.i

# target to preprocess a source file
src/common_star_names.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/common_star_names.cpp.i
.PHONY : src/common_star_names.cpp.i

src/common_star_names.s: src/common_star_names.cpp.s
.PHONY : src/common_star_names.s

# target to generate assembly for a file
src/common_star_names.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/common_star_names.cpp.s
.PHONY : src/common_star_names.cpp.s

src/concurrent_multifile_catalog_v2.o: src/concurrent_multifile_catalog_v2.cpp.o
.PHONY : src/concurrent_multifile_catalog_v2.o

# target to build an object file
src/concurrent_multifile_catalog_v2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/concurrent_multifile_catalog_v2.cpp.o
.PHONY : src/concurrent_multifile_catalog_v2.cpp.o

src/concurrent_multifile_catalog_v2.i: src/concurrent_multifile_catalog_v2.cpp.i
.PHONY : src/concurrent_multifile_catalog_v2.i

# target to preprocess a source file
src/concurrent_multifile_catalog_v2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/concurrent_multifile_catalog_v2.cpp.i
.PHONY : src/concurrent_multifile_catalog_v2.cpp.i

src/concurrent_multifile_catalog_v2.s: src/concurrent_multifile_catalog_v2.cpp.s
.PHONY : src/concurrent_multifile_catalog_v2.s

# target to generate assembly for a file
src/concurrent_multifile_catalog_v2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/concurrent_multifile_catalog_v2.cpp.s
.PHONY : src/concurrent_multifile_catalog_v2.cpp.s

src/gaia_cache.o: src/gaia_cache.cpp.o
.PHONY : src/gaia_cache.o

# target to build an object file
src/gaia_cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_cache.cpp.o
.PHONY : src/gaia_cache.cpp.o

src/gaia_cache.i: src/gaia_cache.cpp.i
.PHONY : src/gaia_cache.i

# target to preprocess a source file
src/gaia_cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_cache.cpp.i
.PHONY : src/gaia_cache.cpp.i

src/gaia_cache.s: src/gaia_cache.cpp.s
.PHONY : src/gaia_cache.s

# target to generate assembly for a file
src/gaia_cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_cache.cpp.s
.PHONY : src/gaia_cache.cpp.s

src/gaia_client.o: src/gaia_client.cpp.o
.PHONY : src/gaia_client.o

# target to build an object file
src/gaia_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_client.cpp.o
.PHONY : src/gaia_client.cpp.o

src/gaia_client.i: src/gaia_client.cpp.i
.PHONY : src/gaia_client.i

# target to preprocess a source file
src/gaia_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_client.cpp.i
.PHONY : src/gaia_client.cpp.i

src/gaia_client.s: src/gaia_client.cpp.s
.PHONY : src/gaia_client.s

# target to generate assembly for a file
src/gaia_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_client.cpp.s
.PHONY : src/gaia_client.cpp.s

src/gaia_mag18_catalog.o: src/gaia_mag18_catalog.cpp.o
.PHONY : src/gaia_mag18_catalog.o

# target to build an object file
src/gaia_mag18_catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog.cpp.o
.PHONY : src/gaia_mag18_catalog.cpp.o

src/gaia_mag18_catalog.i: src/gaia_mag18_catalog.cpp.i
.PHONY : src/gaia_mag18_catalog.i

# target to preprocess a source file
src/gaia_mag18_catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog.cpp.i
.PHONY : src/gaia_mag18_catalog.cpp.i

src/gaia_mag18_catalog.s: src/gaia_mag18_catalog.cpp.s
.PHONY : src/gaia_mag18_catalog.s

# target to generate assembly for a file
src/gaia_mag18_catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog.cpp.s
.PHONY : src/gaia_mag18_catalog.cpp.s

src/gaia_mag18_catalog_v2.o: src/gaia_mag18_catalog_v2.cpp.o
.PHONY : src/gaia_mag18_catalog_v2.o

# target to build an object file
src/gaia_mag18_catalog_v2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog_v2.cpp.o
.PHONY : src/gaia_mag18_catalog_v2.cpp.o

src/gaia_mag18_catalog_v2.i: src/gaia_mag18_catalog_v2.cpp.i
.PHONY : src/gaia_mag18_catalog_v2.i

# target to preprocess a source file
src/gaia_mag18_catalog_v2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog_v2.cpp.i
.PHONY : src/gaia_mag18_catalog_v2.cpp.i

src/gaia_mag18_catalog_v2.s: src/gaia_mag18_catalog_v2.cpp.s
.PHONY : src/gaia_mag18_catalog_v2.s

# target to generate assembly for a file
src/gaia_mag18_catalog_v2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/gaia_mag18_catalog_v2.cpp.s
.PHONY : src/gaia_mag18_catalog_v2.cpp.s

src/iau_star_catalog_parser.o: src/iau_star_catalog_parser.cpp.o
.PHONY : src/iau_star_catalog_parser.o

# target to build an object file
src/iau_star_catalog_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/iau_star_catalog_parser.cpp.o
.PHONY : src/iau_star_catalog_parser.cpp.o

src/iau_star_catalog_parser.i: src/iau_star_catalog_parser.cpp.i
.PHONY : src/iau_star_catalog_parser.i

# target to preprocess a source file
src/iau_star_catalog_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/iau_star_catalog_parser.cpp.i
.PHONY : src/iau_star_catalog_parser.cpp.i

src/iau_star_catalog_parser.s: src/iau_star_catalog_parser.cpp.s
.PHONY : src/iau_star_catalog_parser.s

# target to generate assembly for a file
src/iau_star_catalog_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/iau_star_catalog_parser.cpp.s
.PHONY : src/iau_star_catalog_parser.cpp.s

src/types.o: src/types.cpp.o
.PHONY : src/types.o

# target to build an object file
src/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/types.cpp.o
.PHONY : src/types.cpp.o

src/types.i: src/types.cpp.i
.PHONY : src/types.i

# target to preprocess a source file
src/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/types.cpp.i
.PHONY : src/types.cpp.i

src/types.s: src/types.cpp.s
.PHONY : src/types.s

# target to generate assembly for a file
src/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/types.cpp.s
.PHONY : src/types.cpp.s

src/unified_gaia_catalog.o: src/unified_gaia_catalog.cpp.o
.PHONY : src/unified_gaia_catalog.o

# target to build an object file
src/unified_gaia_catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/unified_gaia_catalog.cpp.o
.PHONY : src/unified_gaia_catalog.cpp.o

src/unified_gaia_catalog.i: src/unified_gaia_catalog.cpp.i
.PHONY : src/unified_gaia_catalog.i

# target to preprocess a source file
src/unified_gaia_catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/unified_gaia_catalog.cpp.i
.PHONY : src/unified_gaia_catalog.cpp.i

src/unified_gaia_catalog.s: src/unified_gaia_catalog.cpp.s
.PHONY : src/unified_gaia_catalog.s

# target to generate assembly for a file
src/unified_gaia_catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ioc_gaialib.dir/build.make CMakeFiles/ioc_gaialib.dir/src/unified_gaia_catalog.cpp.s
.PHONY : src/unified_gaia_catalog.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... iau_integration_test"
	@echo "... integration_test"
	@echo "... ioc_gaialib"
	@echo "... unified_api_demo"
	@echo "... src/common_star_names.o"
	@echo "... src/common_star_names.i"
	@echo "... src/common_star_names.s"
	@echo "... src/concurrent_multifile_catalog_v2.o"
	@echo "... src/concurrent_multifile_catalog_v2.i"
	@echo "... src/concurrent_multifile_catalog_v2.s"
	@echo "... src/gaia_cache.o"
	@echo "... src/gaia_cache.i"
	@echo "... src/gaia_cache.s"
	@echo "... src/gaia_client.o"
	@echo "... src/gaia_client.i"
	@echo "... src/gaia_client.s"
	@echo "... src/gaia_mag18_catalog.o"
	@echo "... src/gaia_mag18_catalog.i"
	@echo "... src/gaia_mag18_catalog.s"
	@echo "... src/gaia_mag18_catalog_v2.o"
	@echo "... src/gaia_mag18_catalog_v2.i"
	@echo "... src/gaia_mag18_catalog_v2.s"
	@echo "... src/iau_star_catalog_parser.o"
	@echo "... src/iau_star_catalog_parser.i"
	@echo "... src/iau_star_catalog_parser.s"
	@echo "... src/types.o"
	@echo "... src/types.i"
	@echo "... src/types.s"
	@echo "... src/unified_gaia_catalog.o"
	@echo "... src/unified_gaia_catalog.i"
	@echo "... src/unified_gaia_catalog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

